#cloud-config
# SSH
disable_root: False
ssh_pwauth: True
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFWxleK9RNC9lxZotL95FttjZkgwrlc5TUawbDsyZRx4 kwentine@localhost"

chpasswd:
  expire: False
  users:
    - name: root
      password: racine
      type: text
    - name: cloud-user
      password: nuage
      type: text

# Users
users:
  - default
  - name: root
    lock_passwd: False
    ssh_authorized_keys: ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFWxleK9RNC9lxZotL95FttjZkgwrlc5TUawbDsyZRx4 kwentine@localhost"]
    shell: /bin/bash

# Package configuration
mounts:
  - [ /dev/cdrom, /mnt/dvd, "iso9660", "ro,defaults,nofail", "0", "0" ]

write_files:
  - path: /etc/vconsole.conf
    content: |
      KEYMAP=se
  - path: /etc/dnf/plugins/subscription-manager.conf
    permissions: "0644"
    content: |
      [main]
      enabled=0
  - path: /etc/rhsm/rhsm.conf
    permissions: "0644"
    append: true
    content: |
      [rhsm]
      manage_repos = 0
  - path: /etc/NetworkManager/conf.d/rke2-canal.conf
    content: |
      [keyfile]
      unmanaged-devices=interface-name:flannel*;interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
  - path: /root/env.bash
    content: |
      export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
      export PATH=/var/lib/rancher/rke2/bin:/var/lib/rancher/rke2/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
      source <(kubectl completion bash)
      export CONTAINER_RUNTIME_ENDPOINT=/run/k3s/containerd/containerd.sock
      export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
yum_repos:
  BaseOS:
    name: RHEL DVD BaseOS
    baseurl: file:///mnt/dvd/BaseOS
    enabled: true
    gpgkey: file:///mnt/dvd/RPM-GPG-KEY-redhat-release
  AppStream:
    name: RHEL DVD AppStream
    baseurl: file:///mnt/dvd/AppStream
    enabled: true
    gpgkey: file:///mnt/dvd/RPM-GPG-KEY-redhat-release
