# Debugging
log-queries
log-dhcp

# Interface and domain
interface=qvm0
local-service=net
bind-interfaces
domain=qvm0.lan

# Ignore /etc/hosts
no-hosts

# Do not forward:
#  - hostname queries (e.g. "cp")
#  - queries in the "qvm0.lan" and "qvm.lan" domain
#  - reverse lookups in private ranges
domain-needed
local=/lan/local/
bogus-priv

# Virtual IPs
address=/qvm.lan/10.42.0.5

# Derive an A record from an interface address
interface-name=bridge.qvm0.lan,qvm0/4

# DHCP range for nodes
dhcp-authoritative
dhcp-range=10.42.0.10,10.42.0.20
