#cloud-config
# Hostname
host: ${QVM_HOST}
# SSH
disable_root: False
ssh_pwauth: True
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFWxleK9RNC9lxZotL95FttjZkgwrlc5TUawbDsyZRx4 kwentine@localhost"
chpasswd:
  expire: False
  users:
    - name: root
      password: racine
      type: text
    - name: cloud-user
      password: nuage
      type: text
# Users
users:
  - default
  - name: root
    lock_passwd: False
    ssh_authorized_keys: ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFWxleK9RNC9lxZotL95FttjZkgwrlc5TUawbDsyZRx4 kwentine@localhost"]
    shell: /bin/bash
# Package configuration
mounts:
  - [/dev/cdrom, /mnt/dvd, "iso9660", "ro,defaults,nofail", "0", "0"]
write_files:
  - path: /etc/vconsole.conf
    content: |
      KEYMAP=se
  - path: /etc/dnf/plugins/subscription-manager.conf
    permissions: "0644"
    content: |
      [main]
      enabled=0
  - path: /etc/rhsm/rhsm.conf
    permissions: "0644"
    append: true
    content: |
      [rhsm]
      manage_repos = 0
  - path: /root/.bashrc
    append: true
    content: |
      export CONTAINER_RUNTIME_ENDPOINT=/run/containerd/containerd.sock
yum_repos:
  BaseOS:
    name: RHEL DVD BaseOS
    baseurl: file:///mnt/dvd/BaseOS
    enabled: true
    gpgkey: file:///mnt/dvd/RPM-GPG-KEY-redhat-release
  AppStream:
    name: RHEL DVD AppStream
    baseurl: file:///mnt/dvd/AppStream
    enabled: true
    gpgkey: file:///mnt/dvd/RPM-GPG-KEY-redhat-release
