#!/usr/bin/env bash
set -eu
#+ Create an overlay VM from a base disk image.
#+ Base images are searched in QVM_DIR/templates,
#+ and VM disks created in QVM_DIR/machines.
#+ Usage: SCRIPT [-n] [-b BASE_NAME] [-s SIZE] VM_NAME

SCRIPT="$(basename "$0")"
SCRIPT_DIR="$(dirname "$0")"
# shellcheck source-path=SCRIPTDIR
source "${SCRIPT_DIR}/libqvm.sh"

#+ Options:
#+ -h  Print this message
#+ -n  Dry run
dry_run=0
#+ -s SIZE  VM disk size.
#+          Example: 20G
#+          Default: same as base image
#+ -b BASE_NAME  Base disk image name, without extension.
#+               Searched in QVM_DIR/templates
base_disk_name=default

while getopts b:s:nh opt; do
  case "${opt}" in
    n)
      dry_run=1
      ;;
    s)
      size="${OPTARG}"
      ;;
    b)
      base_disk_name="${OPTARG}"
      ;;
    *)
      usage "${opt}"
      ;;
  esac
done
shift $((OPTIND - 1))

vm_name="${1:-}"
[[ -n "${vm_name}" ]] || errexit "required: VM_NAME"

vm_disk_file="${QVM_DIR}/machines/${vm_name}.qcow2"

if [[ -f "${base_disk_name}" ]]; then
  base_disk_file="${base_disk_name}"
else
  printf -v base_disk_file '%s/%s.qcow2' "${QVM_DIR}/templates" "${base_disk_name}"
fi

[[ -n "${base_disk_file}" ]] || errexit "no such file: ${base_disk_file}"

args=(
  create
  -f qcow2
  -b "$(realpath --relative-to "${QVM_DIR}/machines" "${base_disk_file}")"
  -F qcow2
  "${vm_disk_file}"
)
if [[ -n "${size:-}" ]]; then
  args+=("${size}")
fi

run qemu-img "${args[@]}"
run qemu-img info "${vm_disk_file}"
