#!/bin/bash
#+ Build cloud-init local datasource for HOST
#+ Usage: SCRIPT [-h] [-u USER_DATA] HOST
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"
# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

QVM_DIR="${QVM_DIR:-/var/vms}"
LOCALDS_DIR="${QVM_DIR}/localds"

user_data="${DIR}/user-data/cloud.yaml"
while getopts hu: opt; do
  case "${opt}" in
    u)
      user_data="${OPTARG}"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

mnt_point="$(mktemp -d /tmp/qvm-localds-XXXX)"
on_exit() {
  sudo umount "${mnt_point}" || true
}

trap on_exit EXIT

create_img() {
  truncate --size 256K "${img}"
  mkfs.vfat -n CIDATA "${img}"
  sudo mount -t vfat "${img}" "${mnt_point}"
  QVM_HOST="${vm}" envsubst <"${user_data}" |
    sudo tee "${mnt_point}/user-data" >/dev/null
}

for vm in "$@"; do
  img="${LOCALDS_DIR}/${vm}.img"
  create_img || errexit "Unable to create image: ${img}"
  info "Created datasource: ${img}"
done
