#!/bin/bash
#+ Setup NAT firewall rules for bridge qvm0
#+
#+ Usage: SCRIPT [up|down]
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"

# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

while getopts dh opt; do
  case "${opt}" in
    d)
      dry_run=1
      ;;
    *)
      usage "${opt}"
      ;;
  esac
done

[[ "$(id -u)" == 0 ]] || errexit "Must be run as root."

up() {
  # Masquerade outbout traffic originating from the bridge
  if run nft -f "${DIR}/net/qvm0.nft"; then
    run nft list table inet qvm
  fi

  # IP forwarding between the bridge and the public host interface
  run sysctl -w net.ipv4.ip_forward=1
}

down() {
  run flush table inet qvm0
}

action="${1:-up}"
case "${action}" in
  up | down)
    "${action}"
    ;;
  *)
    usage "${action}"
    ;;
esac
