#!/usr/bin/env bash
#+ Build cloud-init local datasource for VM
#+ The cloud config file must be named VM and placed in QVM_CONFIG_DIR/user-data
#+ Occurences of ${QVM_HOST} in the cloud config are replace by VM.
#+ Usage: SCRIPT [-h] VM
set -eu
SCRIPT="$(basename "$0")"
SCRIPT_DIR="$(dirname "$0")"
# shellcheck source-path=SCRIPTDIR
source "${SCRIPT_DIR}/libqvm.sh"

LOCALDS_DIR="${QVM_DATA_DIR}/localds"
USERDATA_DIR="${QVM_CONFIG_DIR}/user-data"

while getopts h opt; do
  case "${opt}" in
    *)
      usage "${opt}"
      ;;
  esac
done
shift $((OPTIND - 1))

[[ -n "${1:-}" ]] || usage

vm="${1}"
printf -v user_data '%s/%s' "${USERDATA_DIR}" "${vm}"
[[ -f "${user_data}" ]] || errexit "no such file: ${user_data}"

mnt_point="$(mktemp -d /tmp/qvm-localds-XXXX)"
on_exit() {
  sudo umount "${mnt_point}" || true
}

trap on_exit EXIT

create_img() {
  truncate --size 256K "${img}"
  mkfs.vfat -n CIDATA "${img}"
  sudo mount -t vfat "${img}" "${mnt_point}"
  QVM_HOST="${vm}" envsubst <"${user_data}" |
    sudo tee "${mnt_point}/user-data" >/dev/null
  cat <<EOF | sudo tee "${mnt_point}/meta-data" >/dev/null
instance-id: qvm-${vm}-${RANDOM}
local-hostname: ${vm}
EOF
}

printf -v img "%s/%s.img" "${LOCALDS_DIR}" "${vm}"
create_img || errexit "Unable to create image: ${img}"
info "Created datasource: ${img}"
