#!/bin/env bash
#+ Boot a VM from a disk image in the QVM_DIR/machines directory.
#+ Optionally enable cloud-init, with seed disk in the QVM_DIR/localds directory.
#+ Usage: SCRIPT [-n] [-u] [-d] [-i] VM_NAME
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"
# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

MACHINES_DIR="${QVM_DATA_DIR}/machines"
RUNTIME_DIR="${QVM_DATA_DIR}/run"
LOCALDS_DIR="${QVM_DATA_DIR}/localds"
ISO_DIR="${QVM_DATA_DIR}/iso"

#+ Options:
#+ -h  Print this message and exit.
#+ -i  Enable cloud-init.
cloud_init=0
#+ -n  Dry run. Print the commands that would be executed.
dry_run=0
#+ -d  Daemonize the QEMU process, running it in the background.
detach=0
#+ -u  User mode networking
user_net=0
#+ -r  CDROM  Mount CDROM
cdrom=
#+ -c  Source configuration file
source_config=0

while getopts :hnduicr: opt; do
  case "${opt}" in
    n)
      dry_run=1 ;;
    i)
      cloud_init=1 ;;
    d)
      detach=1 ;;
    u)
      user_net=1 ;;
    r)
      cdrom="${OPTARG}" ;;
    c)
      source_config=1 ;;
    *)
      usage "${opt}" ;;
  esac
done
shift $((OPTIND - 1))

vm="${1:-}"
[[ -n "${vm}" ]] || errexit "Required argument: VM_NAME"

drive="${MACHINES_DIR}/${vm}.qcow2"
[[ -f "${drive}" ]] || errexit "Disk file not found: ${drive}"


config_file="${QVM_CONFIG_DIR}/machines/${vm}"
if ((source_config)); then
  [[ -f "${config_file}" ]] || errexit "Config file not found: ${config_file}"
  # shellcheck disable=SC1090
  source "${config_file}"
fi

args=(
  -name "${vm}"
  -accel kvm
  -cpu host
  -smp "${smp:-4}"
  -m "${m:-8G}"
  -drive "file=${drive},format=qcow2,if=virtio"
  -serial mon:pty
  -display none
)

if [[ -n "${cdrom:-}" ]]; then
  if [[ -f "${cdrom}" ]]; then
    cdrom_file="${cdrom}"
  else
    printf -v cdrom_file '%s/%s.iso' "${ISO_DIR}" "${cdrom}"
  fi
  [[ -f "${cdrom_file}" ]] || errexit "no such file: ${cdrom_file}"
  args+=(
    -cdrom "${cdrom_file}"
  )
fi

if ((cloud_init)); then
  seed="${LOCALDS_DIR}/${vm}.img"
  [[ -e "${seed}" ]] || errexit "Invalid datasource: ${seed}"
  args+=(-drive "file=${seed},if=virtio,format=raw")
fi

# Retrieve this VM's MAC address from static configuration,
# generating a new one if missing.
macaddr() {
  local key="${1:-}"
  local conf="${QVM_CONFIG_DIR}/macs"
  while read -r name macaddr; do
    # When hitting break, macaddr holds the sought address
    [[ "${name}" == "${key}" ]] && break
    macaddr=""
  done <"${conf}"
  if [[ -z "${macaddr:-}" ]]; then
    printf -v macaddr "52:54:%02x:%02x:%02x:%02x" \
           $(( RANDOM & 0xff)) $(( RANDOM & 0xff)) \
           $(( RANDOM & 0xff)) $(( RANDOM & 0xff))
    echo "${key}" "${macaddr}" >> "${conf}"
  fi
  echo "${macaddr}"
}

if ((user_net)); then
  printf -v port "22%02d" $((RANDOM * 100 / 32767 ))
  info "SSH host port: ${port}"
  args+=(-nic "user,model=virtio,hostfwd=tcp::${port}-:22")
else
  args+=(-nic "bridge,br=qvm0,model=virtio,mac=$(macaddr "${vm}")")
fi

# Headless mode (-d option), as opposed to graphical QEMU display
if ((detach)); then
  args+=(
    -daemonize
    -pidfile "${RUNTIME_DIR}/${vm}".pid
  )
fi

run qemu-system-x86_64 "${args[@]}"
