#!/bin/bash
#+ Create a virtual bridge with given name and subnet address.
#+
#+ Usage: SCRIPT [-h] [-d] [-a ADDRESS] [-n NAME] [up|down]
#+
#+ Adapted from:
#+   https://wiki.archlinux.org/title/QEMU/Advanced_networking
#+   https://www.linux-kvm.org/page/Networking

set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"

# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

[[ "$(id -u)" == 0 ]] || errexit "Must be run as root."

#+ Options:
#+ -h  Print this message
#+ -d  Dry run: print the commands that would be executed
#+ -a ADDRESS  Bridge address and subnet. Default: 10.42.0.1/24
br_addr="10.42.0.1/24"
#+ -n NAME  Bridge name. Default: qvm0
br_name="qvm0"
while getopts dhn:a: opt; do
  case "${opt}" in
    d)
      dry_run=1
      ;;
    a)
      br_addr="${OPTARG}"
      ;;
    n)
      br_name="${OPTARG}"
      ;;
    *)
      usage "${opt}"
      ;;
  esac
done
shift $((OPTIND - 1))

up() {
  if ! ip link show "${br_name}" &>/dev/null; then
    run ip link add name "${br_name}" type bridge
    run ip addr add "${br_addr}" dev "${br_name}"
    run ip link set dev "${br_name}" up
  else
    info "Brigde ${br_name} already exists, nothing to create!"
  fi
}

down() {
  if ip link show "${br_name}" &>/dev/null; then
    ip addr del dev "${br_name}" "${br_addr}"
    ip link set dev "${br_name}" down
    ip link delete "${br_name}" type bridge
  else
    info "Brigde ${br_name} does not exists, nothing to remove!"
  fi
}

action="${1:-up}"
case "${action}" in
  up | down)
    "${action}"
    ;;
  *)
    usage "${action}"
    ;;
esac
