#!/bin/env bash
#+ Boot a VM from a disk image in QVM_DATA_DIR/machines.
#+ If found in QVM_DATA_DIR/localds, a cloud-init local data source is added.
#+ Usage: SCRIPT [-n] [-u] [-d] VM
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"
# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

MACHINES_DIR="${QVM_DATA_DIR}/machines"
RUNTIME_DIR="${QVM_DATA_DIR}/run"
LOCALDS_DIR="${QVM_DATA_DIR}/localds"
ISO_DIR="${QVM_DATA_DIR}/iso"

#+ Options:
#+ -h  Print this message and exit.
#+ -n  Dry run. Print the commands that would be executed.
dry_run=0
#+ -d  Daemonize the QEMU process, running it in the background.
detach=0
#+ -u  User mode networking
user_net=0

while getopts :hndu opt; do
  case "${opt}" in
    n)
      dry_run=1 ;;
    d)
      detach=1 ;;
    u)
      user_net=1 ;;
    *)
      usage "${opt}" ;;
  esac
done
shift $((OPTIND - 1))

vm="${1:-}"
[[ -n "${vm}" ]] || errexit "Required argument: VM_NAME"

drive="${MACHINES_DIR}/${vm}.qcow2"
[[ -f "${drive}" ]] || errexit "Disk file not found: ${drive}"

config_file="${QVM_CONFIG_DIR}/machines/${vm}"
if [[ -f "${config_file}" ]]; then
  # shellcheck disable=SC1090
  source "${config_file}"
fi

args=(
  -name "${vm}"
  -accel kvm
  -cpu host
  -smp "${smp:-4}"
  -m "${m:-8G}"
  -drive "file=${drive},format=qcow2,if=virtio"
  -serial mon:pty
  -display none
)

if [[ -n "${cdrom:-}" ]]; then
  if [[ -f "${cdrom}" ]]; then
    cdrom_file="${cdrom}"
  else
    printf -v cdrom_file '%s/%s.iso' "${ISO_DIR}" "${cdrom}"
  fi
  [[ -f "${cdrom_file}" ]] || errexit "no such file: ${cdrom_file}"
  args+=(
    -cdrom "${cdrom_file}"
  )
fi

# Add cloud-init local data source
printf -v localds "%s/%s.img" "${LOCALDS_DIR}" "${vm}"
if [[ -f "${localds}" ]]; then
  args+=(-drive "file=${localds},if=virtio,format=raw")
fi

if ((user_net)); then
  printf -v port "22%02d" $((RANDOM * 100 / 32767 ))
  info "SSH host port: ${port}"
  args+=(-nic "user,model=virtio,hostfwd=tcp::${port}-:22")
else
  if [[ -z "${mac:-}" ]]; then
    printf -v mac "52:54:%02x:%02x:%02x:%02x" \
           $(( RANDOM & 0xff)) $(( RANDOM & 0xff)) \
           $(( RANDOM & 0xff)) $(( RANDOM & 0xff))
  fi
  args+=(-nic "bridge,br=qvm0,model=virtio,mac=${mac}")
fi

# Run in the background
if ((detach)); then
  args+=(
    -daemonize
    -pidfile "${RUNTIME_DIR}/${vm}".pid
  )
fi

run qemu-system-x86_64 "${args[@]}"
